### ISSUE TITLE
Run error

### ISSUE THREAD

**Issue by n15421** [LQSnow/BlockRacing#5]
18:10:15] [Server thread/INFO]: [BlockRacing] Enabling BlockRacing v3.1
[18:10:15] [Server thread/ERROR]: BlockRacing 3.1 encountered a FoException! Please check your error.log and report this issue with the information in that file. Running CraftBukkit 1.21-R0.1-SNAPSHOT and Java 21.0.3
[18:10:15] [Server thread/ERROR]: Error occurred while enabling BlockRacing v3.1 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at org.mineacademy.fo.Common.<clinit>(Common.java:2531) ~[?:?]
        at org.mineacademy.fo.plugin.SimplePlugin.checkServerVersions0(SimplePlugin.java:597) ~[?:?]
        at org.mineacademy.fo.plugin.SimplePlugin.onEnable(SimplePlugin.java:256) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:267) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:492) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_21_R1.CraftServer.enablePlugin(CraftServer.java:567) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]
        at org.bukkit.craftbukkit.v1_21_R1.CraftServer.enablePlugins(CraftServer.java:481) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:641) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:426) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:269) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]
        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1017) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: org.mineacademy.fo.exception.FoException: Report: Your Minecraft version 1.21 is unsupported by BlockRacing
        at org.mineacademy.fo.Valid.checkBoolean(Valid.java:90) ~[?:?]
        at org.mineacademy.fo.remain.Remain.<clinit>(Remain.java:258) ~[?:?]
        ... 14 more

**Comment by LQSnow** [comment]
Currently, the plugin only supports up to version 1.20 and does not support version 1.21 at the moment.
