### ISSUE TITLE
[BUG]最新版无法正常打开面板

### ISSUE THREAD

**Issue by Guailoudou** [LQSnow/BlockRacing#7]
最新版打开面板后台会报错，使用服务端 paper-1.21.1-120
报错内容：
```
[15:55:24 ERROR]: Could not pass event PlayerSwapHandItemsEvent to BlockRacing v3.1
java.lang.ExceptionInInitializerError: null
        at [方块竞速]BlockRacing-3.1.1 (1).jar/top.lqsnow.blockracing.managers.Gui.openMenu(Gui.java:24) ~[[方块竞速]BlockRacing-3.1.1 (1).jar:?]
        at [方块竞速]BlockRacing-3.1.1 (1).jar/top.lqsnow.blockracing.listeners.BasicListener.onPlayerSwapHand(BasicListener.java:43) ~[[方块竞速]BlockRacing-3.1.1 (1).jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:44) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-120-57c75a4]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.1.jar:1.21.1-120-57c75a4]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.1.jar:1.21.1-120-57c75a4]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1794) ~[paper-1.21.1.jar:1.21.1-120-57c75a4]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:51) ~[paper-1.21.1.jar:1.21.1-120-57c75a4]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:20) ~[paper-1.21.1.jar:1.21.1-120-57c75a4]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[paper-1.21.1.jar:1.21.1-120-57c75a4]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.1.jar:1.21.1-120-57c75a4]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.1.jar:1.21.1-120-57c75a4]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.1.jar:1.21.1-120-57c75a4]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1535) ~[paper-1.21.1.jar:1.21.1-120-57c75a4]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.1.jar:1.21.1-120-57c75a4]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.1.jar:1.21.1-120-57c75a4]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1512) ~[paper-1.21.1.jar:1.21.1-120-57c75a4]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1505) ~[paper-1.21.1.jar:1.21.1-120-57c75a4]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.21.1.jar:1.21.1-120-57c75a4]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1464) ~[paper-1.21.1.jar:1.21.1-120-57c75a4]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1471) ~[paper-1.21.1.jar:1.21.1-120-57c75a4]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1316) ~[paper-1.21.1.jar:1.21.1-120-57c75a4]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-120-57c75a4]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.IllegalArgumentException: No enum constant org.bukkit.Sound.LEVEL_UP
        at java.base/java.lang.Enum.valueOf(Enum.java:293) ~[?:?]
        at org.bukkit.Sound.valueOf(Sound.java:13) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at [方块竞速]BlockRacing-3.1.1 (1).jar/org.mineacademy.fo.remain.CompSound.getFallback(CompSound.java:2126) ~[[方块竞速]BlockRacing-3.1.1 (1).jar:?]
        at [方块竞速]BlockRacing-3.1.1 (1).jar/org.mineacademy.fo.remain.CompSound.getSound(CompSound.java:1980) ~[[方块竞速]BlockRacing-3.1.1 (1).jar:?]
        at [方块竞速]BlockRacing-3.1.1 (1).jar/org.mineacademy.fo.menu.Menu.<clinit>(Menu.java:77) ~[[方块竞速]BlockRacing-3.1.1 (1).jar:?]
        ... 26 more
```

**Comment by Guailoudou** [comment]
插件加载过程中报错：
```
[16:04:42 ERROR]: ** COMPATIBILITY TEST FAILED - THIS PLUGIN WILL NOT FUNCTION PROPERLY **
[16:04:42 ERROR]: ** YOUR MINECRAFT VERSION APPEARS UNSUPPORTED: 1.3 **
[16:04:42 WARN]: org.mineacademy.fo.ReflectionUtil$ReflectionException: Could not find class: net.minecraft.server.Entity
[16:04:42 WARN]:        at [方块竞速]BlockRacing-3.1.1 (1).jar//org.mineacademy.fo.ReflectionUtil.lookupClass(ReflectionUtil.java:645)
[16:04:42 WARN]:        at [方块竞速]BlockRacing-3.1.1 (1).jar//org.mineacademy.fo.ReflectionUtil.getNMSClass(ReflectionUtil.java:112)
[16:04:42 WARN]:        at [方块竞速]BlockRacing-3.1.1 (1).jar//org.mineacademy.fo.ReflectionUtil.getNMSClass(ReflectionUtil.java:92)
[16:04:42 WARN]:        at [方块竞速]BlockRacing-3.1.1 (1).jar//org.mineacademy.fo.remain.Remain.<clinit>(Remain.java:266)
[16:04:42 WARN]:        at [方块竞速]BlockRacing-3.1.1 (1).jar//org.mineacademy.fo.Common.<clinit>(Common.java:2531)
[16:04:42 WARN]:        at [方块竞速]BlockRacing-3.1.1 (1).jar//org.mineacademy.fo.model.HookManager.loadDependencies(HookManager.java:161)
[16:04:42 WARN]:        at [方块竞速]BlockRacing-3.1.1 (1).jar//org.mineacademy.fo.plugin.SimplePlugin.onEnable(SimplePlugin.java:277)
[16:04:42 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
[16:04:42 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[16:04:42 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[16:04:42 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
[16:04:42 WARN]:        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640)
[16:04:42 WARN]:        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589)
[16:04:42 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:753)
[16:04:42 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:515)
[16:04:42 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329)
[16:04:42 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214)
[16:04:42 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329)
[16:04:42 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[16:04:42 ERROR]: ***************************************************************
[16:04:42 WARN]: org.mineacademy.fo.ReflectionUtil$ReflectionException: Could not find class: net.minecraft.server.EntityPlayer
[16:04:42 WARN]:        at [方块竞速]BlockRacing-3.1.1 (1).jar//org.mineacademy.fo.ReflectionUtil.lookupClass(ReflectionUtil.java:645)
[16:04:42 WARN]:        at [方块竞速]BlockRacing-3.1.1 (1).jar//org.mineacademy.fo.ReflectionUtil.getNMSClass(ReflectionUtil.java:112)
[16:04:42 WARN]:        at [方块竞速]BlockRacing-3.1.1 (1).jar//org.mineacademy.fo.ReflectionUtil.getNMSClass(ReflectionUtil.java:92)
[16:04:42 WARN]:        at [方块竞速]BlockRacing-3.1.1 (1).jar//org.mineacademy.fo.remain.Remain.<clinit>(Remain.java:298)
[16:04:42 WARN]:        at [方块竞速]BlockRacing-3.1.1 (1).jar//org.mineacademy.fo.Common.<clinit>(Common.java:2531)
[16:04:42 WARN]:        at [方块竞速]BlockRacing-3.1.1 (1).jar//org.mineacademy.fo.model.HookManager.loadDependencies(HookManager.java:161)
[16:04:42 WARN]:        at [方块竞速]BlockRacing-3.1.1 (1).jar//org.mineacademy.fo.plugin.SimplePlugin.onEnable(SimplePlugin.java:277)
[16:04:42 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
[16:04:42 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[16:04:42 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[16:04:42 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
[16:04:42 WARN]:        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640)
[16:04:42 WARN]:        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589)
[16:04:42 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:753)
[16:04:42 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:515)
[16:04:42 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329)
[16:04:42 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214)
[16:04:42 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329)
[16:04:42 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[16:04:46 WARN]: [BlockRacing] Could not save EasyBlocks.txt to plugins/BlockRacing/EasyBlocks.txt because EasyBlocks.txt already exists.
[16:04:46 WARN]: [BlockRacing] Could not save MediumBlocks.txt to plugins/BlockRacing/MediumBlocks.txt because MediumBlocks.txt already exists.
[16:04:46 WARN]: [BlockRacing] Could not save HardBlocks.txt to plugins/BlockRacing/HardBlocks.txt because HardBlocks.txt already exists.
[16:04:46 WARN]: [BlockRacing] Could not save DyedBlocks.txt to plugins/BlockRacing/DyedBlocks.txt because DyedBlocks.txt already exists.
[16:04:46 WARN]: [BlockRacing] Could not save EndBlocks.txt to plugins/BlockRacing/EndBlocks.txt because EndBlocks.txt already exists.
[16:04:46 WARN]: [BlockRacing] Could not save zh_cn.json to plugins/BlockRacing/zh_cn.json because zh_cn.json already exists.
[16:04:46 WARN]: [BlockRacing] Could not save en_us.json to plugins/BlockRacing/en_us.json because en_us.json already exists.
```
无其他任何插件

**Comment by LQSnow** [comment]
已更新，下载最新版本试试

**Comment by Guailoudou** [comment]
> 已更新，下载最新版本试试

经测试，问题已不存在，感谢更新
